name: main
on: 
  push:
    branches:
    - main
  schedule:
    - cron: "57 02 * * *"
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Running
        uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
        
      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install tweepy 
          pip install -r datasCalendar.txt
          
      - name: execute py script # run main.py
      
        env:
          KEY_1: ${{ secrets.KEY_1 }}
          KEY_2: ${{ secrets.KEY_2 }}
          KEY_3: ${{ secrets.KEY_3 }}
          KEY_4: ${{ secrets.KEY_4 }}
        run: python3 tt_astronomico.py
      
   
