name: main
on: 
  push:
    branches:
    - main
  schedule:
    - cron: "0 9 * * *"
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Running
      run: |
        echo "Running!"
