name: main
on: 
  push:
    branches:
    - main
  schedule:
    - cron: "42 23 * * *"
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Running
    env:
      KEY_1: ${{ secrets.KEY_1 }}
      KEY_2: ${{ secrets.KEY_2 }}
      KEY_3: ${{ secrets.KEY_3 }}
      KEY_4: ${{ secrets.KEY_4 }}
      run: |
        echo "Running!"
